### PR TITLE
Minor updates to have notes for fork

### PR DESCRIPTION
**Pull request by sigmavirus24**
Note the Python 2 and 3 compatibility and change the version

### CODE REVIEW

**Comment by lambacck** [comment]
:+1: unless we have plans on contributing upstream.

**Comment by lambacck** [comment]
Also upstream owner still has github activity so we could potentially contact them.

**Comment by sigmavirus24** [comment]
We could, but I think they're not interested in maintaining the package since it hasn't been updated since 2014

**Comment by lambacck** [comment]
It didn't need updating until someone wanted to use Python 3. We should be trying to contribute back. If they don't want to maintain it they should pass over the pypi ownership to someone who will.

**Comment by lambacck** [comment]
https://github.com/dahlia/pghstore/pull/2

**Pull request merged**
